### ISSUE TITLE
How does one import the css?

### ISSUE THREAD

**Issue by CASandmann** [jvictorsoto/chap-timeline#1]
I was very surprised to see this module just published as I happened to need this exact library starting today!  I was able to render the chart even though I'm using React which made the process slightly more complicated.  However, I'm not sure how to import the CSS.  I can see it in the `node_modules/chap-timeline` directory, but when I try

    import "chap-timeline/timeline.css";

I get `Module not found: Error: Cannot resolve module 'img/cluster_bg.png'` among other errors.  Am I doing something wrong?

**Comment by jvictorsoto** [comment]
For images you are going to need webpack url-loader (or image-loader, but url-loader is easier). This is my config for it (if you have some font-loader / svg-loader change the matching options):

```js
      {
        test: /\.(png|woff|woff2|eot|ttf|svg)$/,
        loaders: [
          'url-loader?limit=100000'
        ]
      }
```
After that you can load safely both module & style:

```js
import 'chap-timeline/timeline.css';
import 'chap-timeline/timeline-theme.css';
import links from 'chap-timeline/timeline';


// In my case I use it inside an angular directive...
const timeline = new links.Timeline($element[0]);

```

**Comment by CASandmann** [comment]
This worked for me!  (After I remembered to add `chap-timeline` to our list of css-module exceptions of course) . Thanks!

Though I would suggest adding this information to the "Usage" section of the README =)
